viewer_homepage:
    path:     /
    defaults: { _controller: ViewerBundle:Default:index }

viewer_3D:
    path:    /viewer/{folder}
    defaults: { _controller: ViewerBundle:Default:viewer }
    options:
        expose: true

send_viewer_1:
    path:    /send/viewer
    defaults: { _controller: ViewerBundle:Default:send1 }
    options:
        expose: true

send_viewer_2:
    path:    /send/viewer/{folder}
    defaults: { _controller: ViewerBundle:Default:send2 }
    options:
        expose: true


viewer_malloc:
    path:    /viewer/Malloc
    defaults: { _controller: ViewerBundle:Default:Malloc }
    options:
        expose: true

viewer_setup:
    path:    /viewer/Setup/{folder}
    defaults: { _controller: ViewerBundle:Default:Setup }
    options:
        expose: true