viewer_homepage:
    path:     /
    defaults: { _controller: ViewerBundle:Default:index }

viewer_3D:
    path:    /viewer
    defaults: { _controller: ViewerBundle:Default:viewer }

send_viewer:
    path:    /send/viewer
    defaults: { _controller: ViewerBundle:Default:send }