gestion:
    prefix: /gestion
    resource: "@ViewerBundle/Resources/config/routing/gestion.yml"

viewer_homepage:
    path:     /
    defaults: { _controller: ViewerBundle:Default:index }

viewer_3D:
    path:    /viewer/{md5}
    defaults: { _controller: ViewerBundle:Default:viewer }
    options:
        expose: true

send_viewer_1:
    path:    /send/viewer
    defaults: { _controller: ViewerBundle:Default:send1 }
    options:
        expose: true

send_viewer_2:
    path:    /send/viewer/{folder}
    defaults: { _controller: ViewerBundle:Default:send2 }
    options:
        expose: true

index_cabinet:
    path:     /indexCabinet
    defaults: { _controller: ViewerBundle:Gestion:indexCabinet }
