viewer:
    resource: "@ViewerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#Upload Images JS
oneup_uploader:
    resource: .
    type: uploader