ViewerBundle\Entity\Folder:
    type: entity
    table: null
    repositoryClass: ViewerBundle\Repository\FolderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ref:
            type: string
            length: 255
            nullable: false
        nom:
            type: string
            length: 255
            nullable: true
        mallocmandObj:
            type: string
            length: 255
            nullable: true
        mallocmaxObj:
            type: string
            length: 255
            nullable: true
        mallocmandMtl:
            type: string
            length: 255
            nullable: true
        mallocmaxMtl:
            type: string
            length: 255
            nullable: true
        setupmandObj:
            type: string
            length: 255
            nullable: true
        setupmaxObj:
            type: string
            length: 255
            nullable: true
        setupmandMtl:
            type: string
            length: 255
            nullable: true
        setupmaxMtl:
            type: string
            length: 255
            nullable: true
        md5:
            type: string
            length: 32
            nullable: false
        nbGtS:
            type: integer
            nullable: false
        nbGtI:
            type: integer
            nullable: false
        estimationTraitement:
            type: string
            nullable: false
        accepted:
            type: boolean
            nullable: true


    lifecycleCallbacks: {  }
