ViewerBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: ViewerBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO